workflows:
  ios-workflow:
    name: Build MAUI iOS App
    environment:
      xcode: latest
      vars:
        DOTNET_VERSION: '8.0.100'
    scripts:
      - name: Install .NET SDK
        script: |
          curl -O https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --version $DOTNET_VERSION
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --version
      - name: Install MAUI workload
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet workload install maui
      - name: Restore dependencies
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet restore Controller/Controller.csproj
      - name: Publish iOS build
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet publish Controller/Controller.csproj -f:net8.0-ios -c:Release -p:ArchiveOnBuild=true -p:Platform=iPhone
    artifacts:
      - "**/*.ipa"