workflows:
  maui-ios:
    name: Build MAUI iOS App
    environment:
      xcode: latest
      cocoapods: default
      vars:
        DOTNET_ROOT: /usr/local/share/dotnet
        PATH: /usr/local/share/dotnet:$PATH
    scripts:
      - name: Проверка .NET
        script: |
          dotnet --version
      - name: Установка MAUI workload
        script: |
          dotnet workload install maui
      - name: Восстановление зависимостей
        script: |
          dotnet restore Controller.sln
      - name: Сборка iOS-приложения
        script: |
          dotnet publish Controller/Controller.csproj -f:net8.0-ios -c:Release -p:ArchiveOnBuild=true -p:Platform=iPhone
    artifacts:
      - "**/*.ipa"